Add the results page.
Recycle-Buddy/front-end pull request #9
Opened 2018-08-01 19:11 UTC by hRobert12

Right now it looks kinda bad, so I'm open to suggestions on how to improve this.

2018-08-03 03:46 UTC, AndyCErnst requested changes
Nice start. Sorry I don't have the designs out yet, use the seattle.gov websites as a reference until then.

2018-08-03 03:46 UTC, AndyCErnst commented on src/routes/landing.js
> +              title='Skip search and go to results'
lol, this makes no sense in a final version but fine for now. Actually, a comment saying this is temporary might be nice

2018-08-03 03:46 UTC, AndyCErnst commented on src/routes/results.js
> +  textWithMargin: {
It's a better practice to name your styles after the element they are connected to, not what they do.
When I get time to do the designs, I'm going to stick pretty close to this pattern http://www.seattle.gov/util/MyServices/WhereDoesItGo/GlassCeramics/BrokenGlass/index.htm 
So I'm thinking we will need a style for the result header, one for the action (eg Recycle), and one for the description text.

2018-08-03 03:46 UTC, AndyCErnst commented on src/routes/results.js
> +        <Text style={styles.textWithMargin}>Recycle it</Text>
You can put the icons next to the text, I already have those in the repo. You'll probably want to group the icon and related text in a View together, with the heading text out on its own.

2018-08-03 21:22 UTC, hRobert12 commented
I changed the results page to look more like the Seattle where does it go page.

2018-08-04 01:05 UTC, AndyCErnst requested changes
looking better

2018-08-04 01:05 UTC, AndyCErnst commented on src/assets/images.js
> +    recycleSymbol: require('./images/recycle-symbol.png'), //Robert: Can we have a recycle symbol green?
- comments like this don't belong in the code
- I want to keep the recycle symbol a different color from the compost and trash symbols

2018-08-04 01:05 UTC, AndyCErnst commented on src/routes/results.js
> +          {/*The fact that there is a LOT of whitespace here disturbs me*/}
unhelpful comment

2018-08-04 01:05 UTC, AndyCErnst commented on src/routes/results.js
> +const containerFlex = 1/1;
`1/1 is the same as 1`

2018-08-04 01:05 UTC, AndyCErnst commented on src/routes/landing.js
> +              title='Skip search and go to results' //Defenetly temporary. Eventually the search page will lead to the results page.
spelling, "Definitely"
Even though it's a temporary comment, it's good to keep it professional

2018-08-04 01:05 UTC, AndyCErnst commented on src/routes/results.js
> +    return ( //The info here is hardcoded, but we will enevtually want to make the info change depanding on the item scanned.
spelling

2018-08-07 02:23 UTC, hRobert12 commented
Sorry for those comments in the code, I should have put those on the PR instead of the code. I have cleaned up those comments and fixed the spelling.

2018-08-07 05:22 UTC, AndyCErnst approved these changes
lgtm, nice

2018-08-07 19:52 UTC, merged